- project:
    check:
      jobs:
        - loci-buildset-registry
        # 2023.2 Ubuntu Jammy
        - loci-build-2023-2-ubuntu_jammy
        - loci-compute-kit-2023-2-ubuntu_jammy
        - loci-cinder-2023-2-ubuntu_jammy
        # 2024.1 Ubuntu Jammy
        - loci-build-2024-1-ubuntu_jammy
        - loci-compute-kit-2024-1-ubuntu_jammy
        - loci-cinder-2024-1-ubuntu_jammy
        # 2024.2 Ubuntu Jammy
        - loci-build-2024-2-ubuntu_jammy
        - loci-compute-kit-2024-2-ubuntu_jammy
        - loci-cinder-2024-2-ubuntu_jammy
        # Master Ubuntu Jammy
        - loci-build-master-ubuntu_jammy
    gate:
      jobs:
        - loci-buildset-registry
        - loci-upload-2023-2-ubuntu_jammy
        - loci-upload-2024-1-ubuntu_jammy
        - loci-upload-2024-2-ubuntu_jammy
        - loci-upload-master-ubuntu_jammy
    promote:
      jobs:
        - loci-promote-2023-2-ubuntu_jammy
        - loci-promote-2024-1-ubuntu_jammy
        - loci-promote-2024-2-ubuntu_jammy
        - loci-promote-master-ubuntu_jammy
    periodic:
      jobs:
        - loci-buildset-registry
        # 2023.2 Ubuntu Jammy
        - loci-upload-2023-2-ubuntu_jammy
        - loci-compute-kit-2023-2-ubuntu_jammy
        - loci-cinder-2023-2-ubuntu_jammy
        - loci-promote-2023-2-ubuntu_jammy:
            dependencies:
              - name: loci-compute-kit-2023-2-ubuntu_jammy
              - name: loci-cinder-2023-2-ubuntu_jammy
        # 2024.1 Ubuntu Jammy
        - loci-upload-2024-1-ubuntu_jammy
        - loci-compute-kit-2024-1-ubuntu_jammy
        - loci-cinder-2024-1-ubuntu_jammy
        - loci-promote-2024-1-ubuntu_jammy:
            dependencies:
              - name: loci-compute-kit-2024-1-ubuntu_jammy
              - name: loci-cinder-2024-1-ubuntu_jammy
        # 2024.2 Ubuntu Jammy
        - loci-upload-2024-2-ubuntu_jammy
        - loci-compute-kit-2024-2-ubuntu_jammy
        - loci-cinder-2024-2-ubuntu_jammy
        - loci-promote-2024-2-ubuntu_jammy:
            dependencies:
              - name: loci-compute-kit-2024-2-ubuntu_jammy
              - name: loci-cinder-2024-2-ubuntu_jammy
        # Master Ubuntu Jammy
        - loci-upload-master-ubuntu_jammy
        - loci-promote-master-ubuntu_jammy:
            dependencies:
              - name: loci-upload-master-ubuntu_jammy


