- hosts: localhost
  tasks:
    - name: Vars
      include_vars:
        file: "vars.yaml"

    - name: Job vars
      include_vars:
        file: "{{ item }}"
      loop: "{{ vars_files }}"

    - name: Promote images
      include_role:
        name: promote-container-image
      vars:
        container_images: "{{ openstack_images + [requirements_image] }}"
      # NOTE(kozhukalov): Use loop over image registries once
      # this https://review.opendev.org/c/zuul/zuul-jobs/+/881524 is merged.
        image_registry: "{{ image_registries[1] }}"
      # loop_control:
      #   loop_var: image_registry
      # loop: "{{ image_registries }}"
