image_tag: "2025.2-ubuntu_jammy"
distro_image: "public.ecr.aws/ubuntu/ubuntu:jammy"
openstack_release: "stable/2025.2"
ceph_repo: "deb https://download.ceph.com/debian-squid/ jammy main"
openstack_images:
  - "{{ barbican_image }}"
  - "{{ cinder_image }}"
  - "{{ cloudkitty_image }}"
  - "{{ cyborg_image }}"
  - "{{ designate_image }}"
  - "{{ glance_image }}"
  - "{{ heat_image }}"
  - "{{ horizon_image }}"
  - "{{ ironic_image }}"
  - "{{ keystone_image }}"
  - "{{ magnum_image }}"
  - "{{ manila_image }}"
  - "{{ neutron_image }}"
  - "{{ nova_image }}"
  - "{{ octavia_image }}"
  - "{{ openstack_client_image }}"
  - "{{ placement_image }}"
  - "{{ tacker_image}}"
  - "{{ watcher_image }}"
  - "{{ freezer_image }}"
  - "{{ freezer_api_image }}"
  - "{{ blazar_image }}"
  - "{{ zaqar_image }}"
