image_tag: "master-ubuntu_noble"
distro_image: "ubuntu:noble"
openstack_release: "master"
ceph_repo: "deb https://download.ceph.com/debian-reef/ jammy main"
openstack_images:
  - "{{ barbican_image }}"
  - "{{ cinder_image }}"
  - "{{ cyborg_image }}"
  - "{{ designate_image }}"
  - "{{ glance_image }}"
  - "{{ heat_image }}"
  - "{{ horizon_image }}"
  - "{{ ironic_image }}"
  - "{{ keystone_image }}"
  - "{{ manila_image }}"
  - "{{ neutron_image }}"
  - "{{ nova_image }}"
  - "{{ octavia_image }}"
  - "{{ placement_image }}"
  - "{{ tacker_image}}"
  - "{{ watcher_image }}"
